import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { ReduxProvider } from './features/provider';
import { AppContextProvider } from './features/AppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
        <ReduxProvider>
        <div className='container'>
        <Navbar />
        {children}
        <Footer/>
        </div>
        </ReduxProvider>
        </AppContextProvider>
        </body>
    </html>
  )
}
